[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
todo_program = "7csCH3YZYNZmU7Qos3kG757X99fMtG1eLmHr8ojootkX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/duongpham/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
