[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
stake_program = "Drzahf6sg5fttp1HHRNrCnrGzYTNnpjAzsF5vU5RXgxJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/duongpham/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
